/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_wifidirect_DeviceDetailFragment */

#ifndef _Included_com_example_android_wifidirect_DeviceDetailFragment
#define _Included_com_example_android_wifidirect_DeviceDetailFragment
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_android_wifidirect_DeviceDetailFragment
 * Method:    connect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_wifidirect_WifiDisplayPreviewActivity_start
  (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT jint JNICALL Java_com_example_android_wifidirect_WifiDisplayPreviewActivity_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_wifidirect_DeviceDetailFragment
 * Method:    setSurface
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_android_wifidirect_WifiDisplayPreviewActivity_setSurface
  (JNIEnv *, jobject, jobject);


#ifdef __cplusplus
}
#endif
#endif
