/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cidana_screencap_Capture */

#ifndef _Included_cidana_screencap_Capture
#define _Included_cidana_screencap_Capture
#ifdef __cplusplus
extern "C" {
#endif
typedef enum
{
	eROTATION_0 = 0,
	eROTATION_90 = 1,
	eROTATION_180 = 2,
	eROTATION_270 = 3
}E_ROTATION;
/*
 * Class:     cidana_screencap_Capture
 * Method:    initSC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cidana_screencap_Capture_initSC
  (JNIEnv *, jobject);

/*
 * Class:     cidana_screencap_Capture
 * Method:    setVideoEnable
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_cidana_screencap_Capture_setVideoEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     cidana_screencap_Capture
 * Method:    setDisplayMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cidana_screencap_Capture_setDisplayMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     cidana_screencap_Capture
 * Method:    setVideoRenderMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cidana_screencap_Capture_setVideoRenderMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     cidana_screencap_Capture
 * Method:    setVideoRotate
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_cidana_screencap_Capture_setVideoRotate
  (JNIEnv *, jobject, jint);

/*
 * Class:     cidana_screencap_Capture
 * Method:    cancelConnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cidana_screencap_Capture_cancelConnect
(JNIEnv * env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
