/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cidana_wimo_WiMoCapture */

#ifndef _Included_com_cidana_wimo_WiMoCapture
#define _Included_com_cidana_wimo_WiMoCapture
#ifdef __cplusplus
extern "C" {
#endif

typedef enum tagJNIVIDEOTYPE
{
	JNI_VIDEO_TYPE_RGB565 = 0,
	JNI_VIDEO_TYPE_ARGB4444 = 1,
	JNI_VIDEO_TYPE_ARGB8888 = 2,
	JNI_VIDEO_TYPE_YUV420 = 3,
	JNI_VIDEO_TYPE_YUV422 = 4,
	JNI_VIDEO_TYPE_JPEG = 5,
	JNI_VIDEO_TYPE_TS = 6,
}JNIVIDEOTYPE;

typedef enum tagJNIAUDIOTYPE
{
	JNI_AUDIO_TYPE_PCM = 0,
	JNI_AUDIO_TYPE_AAC = 1,
}JNIAUDIOTYPE;

typedef enum tagJNIVIDEOINTERFACE
{
	JNI_HW_VID_INTERFACE = 0,
	JNI_SW_VID_FRAMEBUFFER = 1,
	JNI_SW_VID_SCREENSHOT = 2,
	JNI_TS_STREAM_INTERFACE = 3,
	JNI_LNV_VIDEO_INTERFACE = 4,
	JNI_HS_VIDEO_INTERFACE = 5,
	JNI_ZTE_VIDEO_INTERFACE = 6,
	JNI_GAME_VIDEO_INTERFACE = 7,
	JNI_HAOLIAN_VIDEO_INTERFACE = 8,
	JNI_XIAOMI2_VIDEO_INTERFACE = 9,
}JNIVIDEOINTERFACE;

typedef enum tagJNIAUDIOINTERFACE
{
	JNI_AUD_DEFAULT = 0,
	JNI_AUDIO_SPEAKER = 1,
	JNI_AUDIO_METHOD_TS = 2,
	JNI_AUDIO_METHOD_LNV = 3,
	JNI_AUDIO_METHOD_HS = 4,
	JNI_AUDIO_METHOD_ZTE = 5,
	JNI_AUDIO_METHOD_GAME = 6,
	JNI_AUDIO_METHOD_HAOLIAN = 7,
	JNI_AUDIO_METHOD_XIAOMI2 = 8,
}JNIAUDIOINTERFACE;

typedef enum tagJNIDEVICEMODEL
{
	JNI_DEVICE_MODEL_DEFAULT = 0,
	JNI_DEVICE_LENOVO_S899T_40 = 1, //Lenovo s899t android4.0.3
	JNI_DEVICE_MOTO_MT887_40 = 2, //Moto MT887 android4.0.3 
}JNIDEVICEMODEL;

typedef enum tagJNIDEVICEVERSION
{
	JNI_SDK_VERSION_DEFAULT = 8,
	JNI_SDK_VERSION_15 = 15, //android4.0.3
}JNIDEVICEVERSION;

typedef enum tagJNICURRENT_TV_ROTATE
{
	JNI_CURRENT_TV_ROTATE_0 = 0,
	JNI_CURRENT_TV_ROTATE_90R = 1,
	JNI_CURRENT_TV_ROTATE_90L = 2
}JNICURRENT_TV_ROTATE;

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    jniInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_jniInit
  (JNIEnv *env, jobject thiz, jint videoMode, jint audioMode);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    jniUnInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_jniUnInit
  (JNIEnv *, jobject);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    startWiMo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_startWiMo
  (JNIEnv *, jobject);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    stopWiMo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_stopWiMo
  (JNIEnv *, jobject);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    sendVideoData
 * Signature: (I[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_sendVideoData
  (JNIEnv * env, jobject thiz, jint dataType, jbyteArray data, jint size, jint width, jint height, jint rotate);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    sendAudioData
 * Signature: (I[BIIII)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_sendAudioData
  (JNIEnv * env, jobject thiz, jint dataType, jbyteArray data, jint size, jint sampleRate, jint bitRate, jint channels);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    setTVRotate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_setTVRotate
  (JNIEnv * env, jobject thiz, jint nTVRotate);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    setVideoRotate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_setVideoRotate
  (JNIEnv * env, jobject thiz, jint rotate);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    checkFb0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_checkFb0
  (JNIEnv *, jobject);

/*
 * Class:     com_cmcc_wimo_WiMoCapture
 * Method:    notifyScreenshotCalled
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cmcc_wimo_WiMoCapture_notifyScreenshotCalled
(JNIEnv * env, jobject thiz, jint shotCalled);

#ifdef __cplusplus
}
#endif
#endif
